config/routes.rb
Rails.application.routes.draw do
  root 'events#index'

  get 'companies' => 'companies#index', as: :companies
  get 'companies/new'
  post 'companies' => 'companies#create'

  get 'volunteers/new'
  post 'volunteers' => 'volunteers#create'

  # Seleção de tipo de conta - empresa ou voluntário
  get 'account/select' => 'users#account', as: :user_account_select

  resources :events
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
# == Schema Information
#
# Table name: companies
#
#  id         :bigint(8)        not null, primary key
#  name       :string(255)
#  phone      :string(255)
#  cnpj       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint(8)
#

class Company < ApplicationRecord
  has_many :events
  belongs_to :user
end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id          :bigint(8)        not null, primary key
#  start_date  :datetime
#  end_date    :datetime
#  latitude    :string(255)
#  longitude   :string(255)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  company_id  :bigint(8)
#  description :text(65535)
#  name        :string(255)
#

class Event < ApplicationRecord
  belongs_to :company
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint(8)        not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  role                   :string(255)
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def company?
    role == 'company'
  end

  def volunteer?
    role == 'volunteer'
  end

  def company
    Company.where(user_id: id).first
  end

  def volunteer
    Volunteer.where(user_id: id).first
  end

  def name
    return company.name if company?
    volunteer.name
  end
end

app/models/volunteer.rb
# == Schema Information
#
# Table name: volunteers
#
#  id         :bigint(8)        not null, primary key
#  phone      :string(255)
#  cpf        :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint(8)
#  name       :string(255)
#

class Volunteer < ApplicationRecord
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :check_user_account_status, unless: :devise_controller?

  protected

  def check_user_account_status
    return if controller_name.in?(['users', 'volunteers', 'companies']) || current_user.blank?
    redirect_to user_account_select_path if current_user.role.nil?
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def index
    @companies = Company.all.order('id DESC')
  end

  # Cria uma empresa e faz o link com o usuário logado
  def create
    company = Company.new(company_params)
    company.user_id = current_user.id
    Company.transaction do
      company.save!
      current_user.update! role: 'company'
    end

    redirect_to events_url, notice: 'Empresa criada com sucesso! :)'
  end

  private

  def company_params
    params.require(:company).permit(:name, :phone, :cnpj)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :check_event_owner, only: [:edit, :update, :destroy]

  def index
    @events = Event.all
  end

  def show
  end

  def new
    @event = Event.new
  end

  def edit
  end

  def create
    @event = Event.new(event_params)
    @event.company = current_user.company

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
    end
  end

  private
    # Checa se o dono do evento é o usuário logado
    def check_event_owner
      if current_user.volunteer? || @event.company != current_user.company
        redirect_to(events_url, notice: 'Você não pode editar esse evento') && return
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :description, :start_date, :end_date, :latitude, :longitude)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def account
    @company = Company.new
    @volunteer = Volunteer.new
    render layout: 'devise'
  end
end

app/controllers/volunteers_controller.rb
class VolunteersController < ApplicationController
  # Cria uma empresa e faz o link com o usuário logado
  def create
    volunteer = Volunteer.new(volunteer_params)
    volunteer.user_id = current_user.id
    Volunteer.transaction do
      volunteer.save!
      current_user.update! role: 'volunteer'
    end

    redirect_to events_url, notice: 'Cadastro criado com sucesso! :)'
  end

  private

  def volunteer_params
    params.require(:volunteer).permit(:name, :phone, :cpf)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/companies/index.html.erb
<section class="app-wrapper">

  <div class="app-block">
    <div class="app-block-title">
      <h3>
        <i class="lnr lnr-apartment"></i> Empresas
      </h3>
    </div>

    <div class="app-block-content">

      <table class="table">
        <thead>
          <tr>
            <th>Nome</th>
            <th>Telefone</th>
          </tr>
        </thead>

        <tbody>
          <% @companies.each do |company| %>
            <tr>
              <td><%= company.name %></td>
              <td><%= company.phone %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

    </div>

  </div>

</section>

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |f| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <% provide :head_tags do %>
    <meta name='turbolinks-visit-control' content='reload'>
    <script>
        document.addEventListener("DOMContentLoaded", initMap);
    </script>
  <% end %>
  <span id="changes" style="display: none">yes</span>
  <div style="width: 50%; margin: auto; background-color: #fff; padding: 1%; border-radius: 4px; box-shadow: 0 2px 2px 0 rgba(0,0,0,.14),0 3px 1px -2px rgba(0,0,0,.2),0 1px 5px 0 rgba(0,0,0,.12);">
    <%= f.label :name, 'Nome' %>
    <%= f.text_field :name, class: 'form-control' %>
    <br>
    <%= f.label :description, 'Descrição' %>
    <%= f.text_area :description, class: 'form-control' %>
    <br>
    <%= f.label :start_date, 'Data de início' %>
    <%= f.text_field :start_date, class: 'air-datepicker-time form-control' %>
    <br>
    <%= f.label :end_date, 'Data de término' %>
    <%= f.text_field :end_date, class: 'air-datepicker-time form-control' %>
    <br>
    <%= f.hidden_field :latitude, class: 'form-control', value: @event.latitude != 0 ? @event.latitude : 0 %>
    <br>
    <%= f.hidden_field :longitude, class:'form-control', value: @event.longitude != 0 ? @event.longitude : 0 %>
    <div id="mapouter2" style="margin: auto; height: 400px; width: 70%;"></div>
    <br>
    <%= f.submit 'Salvar', class: 'btn btn-success' %>
  <div>
    <% provide :head_tags do %>
        <meta name='turbolinks-visit-control' content='reload'>
        <script>
          document.addEventListener("DOMContentLoaded", initMap2);
        </script>
    <% end %>

<% end %>

app/views/events/edit.html.erb
<section class="app-wrapper">
  <div class="app-block">
    <div class="app-block-title">
      <h3><i class="lnr lnr-pencil"></i> Editando evento</h3>

      <%= link_to 'Voltar', @event, class: 'btn' %>
    </div>
    <div class="app-block-content">

      <%= render 'form', event: @event %>
    </div>

    <span id="changes" style="display: none">yes</span>
  </div>
</section>

app/views/events/index.html.erb
<section class="app-wrapper">

  <div class="app-block">
    <div class="app-block-title">
      <h3>
        <i class="lnr lnr-flag"></i> Eventos
      </h3>

      <%= link_to new_event_path, class: 'btn' do %>
        <i class="lnr lnr-plus-circle"></i> Novo evento
      <% end if user_signed_in? && current_user.company? %>
    </div>

    <div class="app-block-content">

      <table class="table">
        <thead>
          <tr>
            <th>Nome</th>
            <th>Data de início</th>
            <th>Data de término</th>
            <th>Empresa</th>
            <th></th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <% @events.each do |event| %>
            <tr>
              <td>
                <%= event.name %>
              </td>
              <td><%= event.start_date.strftime('%d/%m/%Y - %H:%M') %></td>
              <td><%= event.end_date.strftime('%d/%m/%Y - %H:%M') %></td>
              <td><%= event.company.name %></td>
              <td>
                <%= link_to event do %>
                  <i class="lnr lnr-eye"></i> Ver
                <% end %>
              </td>
              <td>
                <% if user_signed_in? && event.company == current_user.company %>
                  <%= link_to edit_event_path(event) do %>
                    <i class="lnr lnr-pencil" title="Editar"></i>
                  <% end %>
                  <%= link_to event, method: :delete, data: { confirm: 'Você tem certeza?' } do %>
                    <i class="lnr lnr-trash" style="color: red" title="Remover"></i>
                  <% end %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>

    </div>

  </div>

</section>

app/views/events/new.html.erb
<h1 style="text-align: center">Novo evento</h1>

<%= render 'form', event: @event %>
<%= link_to 'Voltar', events_path %>

app/views/events/show.html.erb
<section class="app-wrapper">
  <div class="app-block">
    <div class="app-block-title">
      <h3>
        <i class="lnr lnr-flag"></i> <%= @event.name %>
      </h3>

      <%= link_to 'Editar', edit_event_path(@event), class: 'btn' if user_signed_in? && current_user.company == @event.company %>
    </div>

    <div class="app-block-content">

      <p>
        <% if @event.description.present? %>
          <%= @event.description %>
        <% else %>
          Sem descrição
        <% end %>
      </p>

      <p>
        <strong>Data de início:</strong>
        <%= @event.start_date.strftime('%d/%m/%Y - %H:%M') %>
      </p>

      <p>
        <strong>Data de término:</strong>
        <%= @event.end_date.strftime('%d/%m/%Y - %H:%M') %>
      </p>

      <p>
        <strong>Empresa: </strong>
        <%= @event.company.name %>
      </p>

      <p>
        <strong>Contato: </strong>
        <%= @event.company.phone %>
      </p>

      <span id="event_latitude"><%= @event.latitude %></span>
      <span id="event_longitude"><%= @event.longitude %></span>
      <span id="changes" style="display: none">no</span>

      <div id="mapouter" style="margin: auto; height: 400px; width: 70%;"></div>
    </div>
  </div>
</section>
<% provide :head_tags do %>
    <meta name='turbolinks-visit-control' content='reload'>
    <script>
    document.addEventListener("DOMContentLoaded", function(){
        initMap()
    });
    </script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Voluntariza</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'vendor_bootstrap', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'https://maps.googleapis.com/maps/api/js?key=AIzaSyD80lU6FBbV1_lCp-n5w_KJD8vf1OhOu14&callback=initMap' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.linearicons.com/free/1.0.0/icon-font.min.css">
    <%= yield(:head_tags) %>
  </head>

  <body class="application-body">

    <%= render 'layouts/partials/header' %>

    <%= yield %>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Voluntariza</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'vendor_bootstrap', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'devise', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.linearicons.com/free/1.0.0/icon-font.min.css">
  </head>

  <body class="text-center">
    <%= yield %>
  </body>
</html>

app/views/layouts/partials/_header.html.erb
<header class="app-header">
  <div class="app-wrapper app-header-wrapper">
    <div class="app-header-logo">
      <h2>Voluntariza</h2>
    </div>

    <ul class="app-header-list">
      <li>
        <%= link_to events_path, class: "#{'active' if controller_name == 'events'}" do %>
          <i class="lnr lnr-calendar-full"></i> Eventos
        <% end %>
      </li>
      <li>
        <%= link_to companies_path, class: "#{'active' if controller_name == 'companies'}" do %>
          <i class="lnr lnr-apartment"></i> Empresas
        <% end %>
      </li>
    </ul>

    <div class="app-header-login">
      <% if user_signed_in? %>
        <i class="lnr lnr-user"></i> Olá, <%= current_user.name %>! <small><%= link_to 'Sair', destroy_user_session_path, method: :delete, style: "border: 1px solid rgb(244, 67, 54); color: white; padding: 4px; background: rgb(244, 67, 54); border-radius: 4px; box-shadow: 0 2px 2px 0 rgba(0,0,0,.14),0 3px 1px -2px rgba(0,0,0,.2),0 1px 5px 0 rgba(0,0,0,.12); margin-left: 2px;" %></small>
      <% else %>
        <%= link_to 'Entrar / Cadastrar', new_user_session_path, style:"color: white" %>
      <% end %>
    </div>
  </div>
</header>

app/views/users/account.html.erb
<section class="app-flex account">
  <div style='background-color: #fff; padding: 1%; box-shadow: 0 2px 2px 0 rgba(0,0,0,.14),0 3px 1px -2px rgba(0,0,0,.2),0 1px 5px 0 rgba(0,0,0,.12);'>
    <i class="lnr lnr-apartment" style="font-size: 4em"></i>
    <h1 class="h3 mb-3 font-weight-normal">
      Empresa
    </h1>

    <%= form_for @company do |f| %>

      <%= f.text_field :name, placeholder: 'Nome', class: 'form-control top',  style: 'margin-bottom:4px'  %>

      <%= f.text_field :phone, placeholder: 'Telefone', class: 'form-control middle',  style: 'margin-bottom:4px'  %>

      <%= f.text_field :cnpj, placeholder: 'CNPJ', class: 'form-control bottom'  %>

      <br>

      <%= f.submit 'Cadastrar', class: 'btn btn-lg btn-block btn-primary' %>

    <% end %>
  </div>
  <div class="col" style='background-color: #fff; padding: 1%; box-shadow: 0 2px 2px 0 rgba(0,0,0,.14),0 3px 1px -2px rgba(0,0,0,.2),0 1px 5px 0 rgba(0,0,0,.12);' >
    <i class="lnr lnr-user" style="font-size: 4em"></i>
    <h1 class="h3 mb-3 font-weight-normal">
      Voluntário
    </h1>

    <%= form_for @volunteer do |f| %>
      <%= f.text_field :name, placeholder: 'Nome', class: 'form-control top',  style: 'margin-bottom:4px'  %>

      <%= f.text_field :phone, placeholder: 'Telefone', class: 'form-control middle',  style: 'margin-bottom:4px'  %>

      <%= f.text_field :cpf, placeholder: 'CPF', class: 'form-control bottom' %>

      <br>

      <%= f.submit 'Cadastrar', class: 'btn btn-lg btn-block btn-primary' %>

    <% end %>

  </div>
</section>